# #The Monty Hall Problem

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
def simulate_prizedoor(nsim):
    prizeloc =[]
    for idx in np.arange(nsim):
        prizeloc.append(np.random.randint(0,3))
    return np.asarray(prizeloc)

In [3]:
print simulate_prizedoor(4)

[0 2 2 0]


Now simulate the guesses by the contestant

In [4]:
def simulate_guess(nsim):
    guess = []
    for idx in np.arange(nsim):
        guess.append(np.random.randint(0,3))
    return np.asarray(guess)

In [5]:
print simulate_guess(4)

[2 1 1 1]


Simulate the opening of a door that reveals the location of one of the goats. 
This location must be different from the prize door and from the contestant's guess. 
- if prizeloc == guess, return random between the two remaining doors
- if prizeloc != guess, return the remaining door

In [6]:
def goat_door(prizeloc, guess):
    goat = []
    for idx in np.arange(len(prizeloc)):
        if prizeloc[idx] == guess[idx]:
            x = sorted(np.setxor1d([0,1,2],guess[idx]))
            y = np.random.choice(x)
            goat.append(y)
        elif prizeloc[idx] != guess[idx]:
            y = (prizeloc[idx],guess[idx])
            x = int(np.setxor1d([0,1,2],y))
            goat.append(x)
    return goat

Write a function, switch_guess, that represents the strategy of always switching a guess after the goat door is opened.

In [12]:
def switch_guess(guessdoor, goatdoor):
    switched = []
    for idx in np.arange(len(guessdoor)):
        y = (guessdoor[idx], goatdoor[idx])
        x = int(np.setxor1d([0,1,2],y))
        switched.append(x)
    return switched

In [14]:
prizeloc = simulate_prizedoor(4)
guess = simulate_guess(4)
goat = goat_door(prizeloc, guess)
print prizeloc
print guess
print goat
print switch_guess(guess, goat)

[0 0 1 0]
[1 2 2 2]
[2, 1, 0, 1]
[0, 0, 1, 0]


Last function: write a win_percentage function that takes an array of guesses and prizedoors, and returns the percent of correct guesses

In [38]:
def win_percentage(guess, prizeloc):
    count = 0
    for idx in np.arange(len(guess)):
        if guess[idx]==prizeloc[idx]:
            count += 1
    return float(count)/len(guess)

Now, put it together. Simulate 10000 games where contestant keeps his original guess, and 10000 games where the contestant switches his door after a goat door is revealed. Compute the percentage of time the contestant wins under either strategy. Is one strategy better than the other?

In [44]:
prizeloc = simulate_prizedoor(10000)
guess = simulate_guess(10000)
goat = goat_door(prizeloc, guess)
x = win_percentage(guess, prizeloc)
switched_guess = switch_guess(guess, goat)
y = win_percentage(switched_guess, prizeloc)
print 'Win %f of the times without switching'%(x)
print 'Win %f of the time with switching'%(y)

Win 0.339600 of the times without switching
Win 0.660400 of the time with switching
